apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdn-app
  name: sdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdn-app
  template:
    metadata:
      labels:
        app: sdn-app
    spec:
      containers:
      - image: tqhuy812/nssr-controller-ofc2023:1.0.0
        name: t-sdnc
        stdin: true
        tty: true
