apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sdn-app
  name: sdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdn-app
  template:
    metadata:
      labels:
        app: sdn-app
    spec:
    initContainers:
      - name: init-kafka
        image: busybox:latest
        command: ['sh', '-c', '"until nslookup kafka-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for kafka; sleep 2; done"']
    containers:
      - image: tqhuy812/nssr-controller-ofc2023
        name: t-sdnc
        stdin: true
        tty: true
