apiVersion: v1
kind: Service
metadata:
  labels:
    app: sdn-app
  name: sdn-svc
spec:
  ports:
  - name: cli-sdn
    nodePort: 30101
    port: 8101
    targetPort: 8101
  - name: gui-sdn
    nodePort: 30181
    port: 8181
  selector:
    app: sdn-app
  type: NodePort
