apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-app
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - image: qphamvan/kafka
        name: kafka-broker
        stdin: true
        tty: true
