apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-app
  name: kafka-svc
spec:
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-app
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
      - image: bashj79/kafka-kraft
        name: kafka-broker
        stdin: true
        tty: true
