apiVersion: v1
kind: Service
metadata:
  labels:
    app: oia-pce-app
  name: oia-pce-svc
spec:
  ports:
  - name: drpy-port
    port: 40000
    protocol: TCP
    targetPort: 40000
  selector:
    app: oia-pce-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oia-pce-app
  name: oia-pce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oia-pce-app
  template:
    metadata:
      labels:
        app: oia-pce-app
    spec:
      containers:
      - image: tqhuy812/oia-pce
        name: oia-pce
        stdin: true
        tty: true
