apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ols-controller-app
  name: ols-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols-controller-app
  template:
    metadata:
      labels:
        app: ols-controller-app
    spec:
      containers:
      - image: ols-ofc2023:1.0.0
        name: ols-controller
        stdin: true
        tty: true
