apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols-controller-app
  name: ols-controller-svc
spec:
  ports:
  - name: cli-ols
    nodePort: 30101
    port: 8101
    targetPort: 8101
  - name: gui-ols
    nodePort: 30181
    port: 8181
  selector:
    app: ols-controller-app
  type: NodePort
