apiVersion: v1
kind: Service
metadata:
  name: ols-controller-svc
  labels:
    app: ols-controller-app
spec:
  type: NodePort
  ports:
  - name: cli-ols
    port: 8101
    targetPort: 8101
    nodePort: 30101
  - name: gui-ols
    port: 8181
    nodePort: 30181
  selector:
    app: ols-controller-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ols-controller
  labels:
    app: ols-controller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols-controller-app
  template:
    metadata:
      labels:
        app: ols-controller-app
    spec:
      containers:
        - name: ols-controller
          image: tqhuy812/ols-controller
          stdin: true
          tty: true