apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols-controller-app
  name: ols-controller-svc
spec:
  ports:
  - name: cli-ols
    nodePort: 30101
    port: 8101
    targetPort: 8101
  - name: gui-ols
    nodePort: 30181
    port: 8181
  selector:
    app: ols-controller-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ols-controller-app
  name: ols-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols-controller-app
  template:
    metadata:
      labels:
        app: ols-controller-app
    spec:
      containers:
      - image: tqhuy812/ols-controller
        name: ols-controller
        stdin: true
        tty: true
