apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tapi-ui-app
  name: tapi-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapi-ui-app
  template:
    metadata:
      labels:
        app: tapi-ui-app
    spec:
      containers:
      - image: nginx
        name: docker pull hthieu/opticalgui:v4.0.0
        stdin: true
        tty: true
