apiVersion: v1
kind: Service
metadata:
  labels:
    app: tapi-ui-app
  name: tapi-ui-svc
spec:
  ports:
  - name: http-port
    port: 40000
    protocol: TCP
    targetPort: 8001
  selector:
    app: tapi-ui-app
  type: NodePort
